# Generated by Django 5.1.4 on 2025-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[('Deposit', 1), (2, 'withdrawal'), (3, 'Loan'), (4, 'Loan Paid')], null=True),
        ),
    ]
