# Generated by Django 5.1.4 on 2025-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'withdrawal'), (3, 'Loan'), (4, 'Loan Paid')], null=True),
        ),
    ]
